# Автоматический подбор гиперпараметров для классификаторов и применение LSA к предобработке тектсов

## 1. Загрузка необходимых библиотек и данных

In [31]:
import re
import pandas as pd
from datasets import load_dataset

from sklearn.datasets import fetch_20newsgroups

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.tree import DecisionTreeClassifier
from  sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier

from sklearn.metrics import f1_score

import nltk
from nltk.corpus import stopwords, wordnet
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\alesh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\alesh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alesh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\alesh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\alesh\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\alesh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.

True

### 1.1 Загрузка датасета emotion

In [32]:
dataset_emotion_train = load_dataset('emotion', split='train')
dataset_emotion_test = load_dataset('emotion', split='test')

print(f"emotion train size: {len(dataset_emotion_train)}")
print(f"emotion test size: {len(dataset_emotion_test)}")

emotion train size: 16000
emotion test size: 2000

### 1.2 Загрузка датачета 20newsgroups(только указанные  категории)

In [33]:
categories = ['comp.sys.ibm.pc.hardware',
              'comp.sys.mac.hardware',
              'comp.graphics',
              'comp.windows.x']

dataset_news_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
dataset_news_test = fetch_20newsgroups(subset='test', categories=categories,shuffle=True, random_state=42)

print(f"news train size: {len(dataset_news_train.data)}")
print(f"news test size: {len(dataset_news_test.data)}")

news train size: 2345
news test size: 1561

## 2. Предобработка текстов

### 2.1 Удаление шума(для news)

In [34]:
def clean_noise(text):
    text = re.sub(r'^(From|Subject|Organization|Lines|Distribution|NNTP-Posting-Host|Keywords|Summary):.*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'^>.*$', '', text, flags=re.MULTILINE)
    lines = text.split('\n')
    cleaned_lines = []
    for line in lines:
        if len(line) == 0:
            continue
        non_alnum = sum(1 for c in line if not c.isalnum() and not c.isspace())
        if non_alnum/len(line) > 0.7 and len(line) > 10:
            continue
        cleaned_lines.append(line)
    text = '\n'.join(cleaned_lines)
    text= re.sub(r'\S+@\S+', '', text)
    text = re.sub(r"[^\w\s.!?']", '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

### 2.2 Токенизация, стемминг, лемматизация, лемматизация(только сущ и прил), LSA

In [35]:
def get_wordnet_pos(tag):
    """Преобразует тег POS из NLTK в формат WordNet."""
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [36]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def tokenize_text(text):
    words = nltk.word_tokenize(text.lower())
    words = [w for w in words if w not in stop_words]
    return ' '.join(words)

def stem_text(text):
    words = nltk.word_tokenize(text.lower())
    words = [stemmer.stem(w) for w in words if w not in stop_words]
    return ' '.join(words)

def lemmatize_text(text):
    words = nltk.word_tokenize(text.lower())
    pos_tags = nltk.pos_tag(words)
    lemmarized_words = []
    for word, tag in pos_tags:
        if word not in stop_words:
            wordnet_tag = get_wordnet_pos(tag)
            lemmarized_words.append(lemmatizer.lemmatize(word, pos=wordnet_tag))
    return ' '.join(lemmarized_words)

def lemmatize_noun_adj_text(text):
    words = nltk.word_tokenize(text.lower())
    pos_tags = nltk.pos_tag(words)
    lemmarized_words = []
    for word, tag in pos_tags:
        if word not in stop_words:
            if tag.startswith('NN') or tag.startswith('J'):
                wordnet_tag = get_wordnet_pos(tag)
                lemmarized_words.append(lemmatizer.lemmatize(word, pos=wordnet_tag))
    return ' '.join(lemmarized_words)

In [37]:
preprocessors = {
    'tokenization': tokenize_text,
    'stemming': stem_text,
    'lemmatization': lemmatize_text,
    'lemmatization_noun_adj': lemmatize_noun_adj_text
}

### 2.3 Применение предобработки

In [38]:
emotion_train_texts = dataset_emotion_train['text']
emotion_train_labels = dataset_emotion_train['label']
emotion_test_texts = dataset_emotion_test['text']
emotion_test_labels = dataset_emotion_test['label']

In [39]:
news_train_texts = [clean_noise(text) for text in dataset_news_train.data]
news_test_texts = [clean_noise(text) for text in dataset_news_test.data]
news_train_labels = dataset_news_train.target
news_test_labels = dataset_news_test.target

In [40]:
processed_train = {'emotion': {}, 'news': {}}
processed_test = {'emotion': {}, 'news': {}}

In [41]:
for prep_name, prep_func in preprocessors.items():
    print(f"Processing emotion with {prep_name}...")
    processed_train['emotion'][prep_name] = [prep_func(text) for text in emotion_train_texts]
    processed_test['emotion'][prep_name] = [prep_func(text) for text in emotion_test_texts]

Processing emotion with tokenization...
Processing emotion with stemming...
Processing emotion with lemmatization...
Processing emotion with lemmatization_noun_adj...

In [42]:
for prep_name, prep_func in preprocessors.items():
    print(f"Processing emotion with {prep_name}...")
    processed_train['news'][prep_name] = [prep_func(text) for text in news_train_texts]
    processed_test['news'][prep_name] = [prep_func(text) for text in news_test_texts]

Processing emotion with tokenization...
Processing emotion with stemming...
Processing emotion with lemmatization...
Processing emotion with lemmatization_noun_adj...

## 3. Векторизаторы и классификаторы

In [85]:
vectorizers = {
    'binary': CountVectorizer(binary=True),
    'count': CountVectorizer(binary=False),
    'tfidf': TfidfVectorizer()
}

classifiers = {
    'DecisionTreeClassifier': DecisionTreeClassifier(random_state=42),
    'RandomForestClassifier': RandomForestClassifier(random_state=42),
    'GradientBoostingClassifier': GradientBoostingClassifier(random_state=42),
    'AdaBoostClassifier': AdaBoostClassifier(estimator=DecisionTreeClassifier(random_state=42),random_state=42)
}

In [44]:
results = []
dataset_names = ['emotion', 'news']

## 4. Цикл экспериментов (по всем датасетам, предобработкам, векторизаторам и классификаторам)

In [45]:
for dataset_name in dataset_names:
    print(f"\n=============== ДАТАСЕТ:{dataset_name.upper()} ==============")
    y_train = emotion_train_labels if dataset_name == 'emotion' else news_train_labels
    y_test = emotion_test_labels if dataset_name == 'emotion' else news_test_labels

    for prep_name in preprocessors.keys():
        X_train_prep = processed_train[dataset_name][prep_name]
        X_test_prep = processed_test[dataset_name][prep_name]

        for vec_name, vectorizer in vectorizers.items():
            print(f"\nПредобработка: {prep_name}, Векторизация: {vec_name}")
            X_train_vec = vectorizer.fit_transform(X_train_prep)
            X_test_vec = vectorizer.transform(X_test_prep)

            for clf_name, clf in classifiers.items():
                clf.fit(X_train_vec, y_train)
                y_pred = clf.predict(X_test_vec)

                f1_micro = f1_score(y_test, y_pred, average='micro')
                f1_macro = f1_score(y_test, y_pred, average='macro')
                f1_weighted = f1_score(y_test, y_pred, average='weighted')

                results.append({
                    'Dataset': dataset_name,
                    'Preprocessing': prep_name,
                    'Vectorizer': vec_name,
                    'Classifier': clf_name,
                    'F1_micro': f1_micro,
                    'F1_macro': f1_macro,
                    'F1_weighted': f1_weighted
                })
                print(f"{clf_name}: micro={f1_micro:.4f}, macro={f1_macro:.4f}, weighted={f1_weighted:.4f}")

=============== ДАТАСЕТ:EMOTION ==============

Предобработка: tokenization, Векторизация: binary
DecisionTreeClassifier: micro=0.8680, macro=0.8070, weighted=0.8687
RandomForestClassifier: micro=0.8835, macro=0.8251, weighted=0.8830
GradientBoostingClassifier: micro=0.8445, macro=0.8001, weighted=0.8452
AdaBoostClassifier: micro=0.3480, macro=0.0900, weighted=0.1867

Предобработка: tokenization, Векторизация: count
DecisionTreeClassifier: micro=0.8675, macro=0.8039, weighted=0.8684
RandomForestClassifier: micro=0.8870, macro=0.8262, weighted=0.8867
GradientBoostingClassifier: micro=0.8440, macro=0.8002, weighted=0.8445
AdaBoostClassifier: micro=0.3480, macro=0.0900, weighted=0.1867

Предобработка: tokenization, Векторизация: tfidf
DecisionTreeClassifier: micro=0.8630, macro=0.8062, weighted=0.8635
RandomForestClassifier: micro=0.8855, macro=0.8211, weighted=0.8838
GradientBoostingClassifier: micro=0.8440, macro=0.8003, weighted=0.8441
AdaBoostClassifier: micro=0.3480, macro=0.0896, weighted=0.1858

Предобработка: stemming, Векторизация: binary
DecisionTreeClassifier: micro=0.7975, macro=0.7326, weighted=0.8013
RandomForestClassifier: micro=0.8455, macro=0.7779, weighted=0.8462
GradientBoostingClassifier: micro=0.7895, macro=0.7536, weighted=0.7915
AdaBoostClassifier: micro=0.3540, macro=0.1042, weighted=0.1955

Предобработка: stemming, Векторизация: count
DecisionTreeClassifier: micro=0.7935, macro=0.7278, weighted=0.7984
RandomForestClassifier: micro=0.8480, macro=0.7823, weighted=0.8488
GradientBoostingClassifier: micro=0.7900, macro=0.7513, weighted=0.7920
AdaBoostClassifier: micro=0.3540, macro=0.1042, weighted=0.1955

Предобработка: stemming, Векторизация: tfidf
DecisionTreeClassifier: micro=0.7935, macro=0.7237, weighted=0.7954
RandomForestClassifier: micro=0.8590, macro=0.7977, weighted=0.8590
GradientBoostingClassifier: micro=0.7970, macro=0.7616, weighted=0.7984
AdaBoostClassifier: micro=0.3545, macro=0.1041, weighted=0.1954

Предобработка: lemmatization, Векторизация: binary
DecisionTreeClassifier: micro=0.8240, macro=0.7663, weighted=0.8250
RandomForestClassifier: micro=0.8615, macro=0.7981, weighted=0.8606
GradientBoostingClassifier: micro=0.7985, macro=0.7631, weighted=0.7993
AdaBoostClassifier: micro=0.3505, macro=0.0957, weighted=0.1890

Предобработка: lemmatization, Векторизация: count
DecisionTreeClassifier: micro=0.8255, macro=0.7615, weighted=0.8270
RandomForestClassifier: micro=0.8610, macro=0.7977, weighted=0.8598
GradientBoostingClassifier: micro=0.7980, macro=0.7640, weighted=0.7989
AdaBoostClassifier: micro=0.3505, macro=0.0957, weighted=0.1890

Предобработка: lemmatization, Векторизация: tfidf
DecisionTreeClassifier: micro=0.8325, macro=0.7816, weighted=0.8330
RandomForestClassifier: micro=0.8605, macro=0.7978, weighted=0.8583
GradientBoostingClassifier: micro=0.7980, macro=0.7633, weighted=0.7994
AdaBoostClassifier: micro=0.3510, macro=0.0973, weighted=0.1920

Предобработка: lemmatization_noun_adj, Векторизация: binary
DecisionTreeClassifier: micro=0.6720, macro=0.5955, weighted=0.6703
RandomForestClassifier: micro=0.7025, macro=0.6287, weighted=0.6998
GradientBoostingClassifier: micro=0.6815, macro=0.6362, weighted=0.6791
AdaBoostClassifier: micro=0.3520, macro=0.0978, weighted=0.1928

Предобработка: lemmatization_noun_adj, Векторизация: count
DecisionTreeClassifier: micro=0.6800, macro=0.6011, weighted=0.6780
RandomForestClassifier: micro=0.7010, macro=0.6249, weighted=0.6977
GradientBoostingClassifier: micro=0.6825, macro=0.6363, weighted=0.6797
AdaBoostClassifier: micro=0.3520, macro=0.0978, weighted=0.1928

Предобработка: lemmatization_noun_adj, Векторизация: tfidf
DecisionTreeClassifier: micro=0.6780, macro=0.6038, weighted=0.6759
RandomForestClassifier: micro=0.7120, macro=0.6398, weighted=0.7077
GradientBoostingClassifier: micro=0.6875, macro=0.6385, weighted=0.6847
AdaBoostClassifier: micro=0.3515, macro=0.0971, weighted=0.1915

=============== ДАТАСЕТ:NEWS ==============

Предобработка: tokenization, Векторизация: binary
DecisionTreeClassifier: micro=0.6092, macro=0.6099, weighted=0.6097
RandomForestClassifier: micro=0.7668, macro=0.7675, weighted=0.7675
GradientBoostingClassifier: micro=0.7489, macro=0.7537, weighted=0.7535
AdaBoostClassifier: micro=0.5791, macro=0.5850, weighted=0.5851

Предобработка: tokenization, Векторизация: count
DecisionTreeClassifier: micro=0.6150, macro=0.6156, weighted=0.6154
RandomForestClassifier: micro=0.7643, macro=0.7652, weighted=0.7652
GradientBoostingClassifier: micro=0.7425, macro=0.7475, weighted=0.7474
AdaBoostClassifier: micro=0.5791, macro=0.5850, weighted=0.5851

Предобработка: tokenization, Векторизация: tfidf
DecisionTreeClassifier: micro=0.6163, macro=0.6170, weighted=0.6167
RandomForestClassifier: micro=0.7438, macro=0.7448, weighted=0.7447
GradientBoostingClassifier: micro=0.7309, macro=0.7335, weighted=0.7334
AdaBoostClassifier: micro=0.5625, macro=0.5711, weighted=0.5713

Предобработка: stemming, Векторизация: binary
DecisionTreeClassifier: micro=0.6137, macro=0.6145, weighted=0.6144
RandomForestClassifier: micro=0.7681, macro=0.7682, weighted=0.7682
GradientBoostingClassifier: micro=0.7636, macro=0.7666, weighted=0.7666
AdaBoostClassifier: micro=0.5746, macro=0.5766, weighted=0.5766

Предобработка: stemming, Векторизация: count
DecisionTreeClassifier: micro=0.6079, macro=0.6098, weighted=0.6097
RandomForestClassifier: micro=0.7681, macro=0.7681, weighted=0.7681
GradientBoostingClassifier: micro=0.7604, macro=0.7638, weighted=0.7637
AdaBoostClassifier: micro=0.5746, macro=0.5766, weighted=0.5766

Предобработка: stemming, Векторизация: tfidf
DecisionTreeClassifier: micro=0.6111, macro=0.6124, weighted=0.6123
RandomForestClassifier: micro=0.7521, macro=0.7526, weighted=0.7526
GradientBoostingClassifier: micro=0.7502, macro=0.7522, weighted=0.7521
AdaBoostClassifier: micro=0.5919, macro=0.5981, weighted=0.5980

Предобработка: lemmatization, Векторизация: binary
DecisionTreeClassifier: micro=0.5887, macro=0.5892, weighted=0.5892
RandomForestClassifier: micro=0.7630, macro=0.7634, weighted=0.7633
GradientBoostingClassifier: micro=0.7553, macro=0.7589, weighted=0.7588
AdaBoostClassifier: micro=0.5983, macro=0.6047, weighted=0.6046

Предобработка: lemmatization, Векторизация: count
DecisionTreeClassifier: micro=0.6015, macro=0.6016, weighted=0.6015
RandomForestClassifier: micro=0.7726, macro=0.7729, weighted=0.7728
GradientBoostingClassifier: micro=0.7527, macro=0.7563, weighted=0.7562
AdaBoostClassifier: micro=0.5900, macro=0.5952, weighted=0.5949

Предобработка: lemmatization, Векторизация: tfidf
DecisionTreeClassifier: micro=0.6156, macro=0.6161, weighted=0.6160
RandomForestClassifier: micro=0.7675, macro=0.7677, weighted=0.7677
GradientBoostingClassifier: micro=0.7380, macro=0.7393, weighted=0.7391
AdaBoostClassifier: micro=0.5926, macro=0.5992, weighted=0.5994

Предобработка: lemmatization_noun_adj, Векторизация: binary
DecisionTreeClassifier: micro=0.6259, macro=0.6268, weighted=0.6267
RandomForestClassifier: micro=0.7617, macro=0.7625, weighted=0.7623
GradientBoostingClassifier: micro=0.7425, macro=0.7469, weighted=0.7468
AdaBoostClassifier: micro=0.5791, macro=0.5904, weighted=0.5903

Предобработка: lemmatization_noun_adj, Векторизация: count
DecisionTreeClassifier: micro=0.6131, macro=0.6140, weighted=0.6139
RandomForestClassifier: micro=0.7604, macro=0.7617, weighted=0.7616
GradientBoostingClassifier: micro=0.7373, macro=0.7420, weighted=0.7419
AdaBoostClassifier: micro=0.5823, macro=0.5900, weighted=0.5898

Предобработка: lemmatization_noun_adj, Векторизация: tfidf
DecisionTreeClassifier: micro=0.6163, macro=0.6176, weighted=0.6175
RandomForestClassifier: micro=0.7438, macro=0.7452, weighted=0.7450
GradientBoostingClassifier: micro=0.7309, macro=0.7345, weighted=0.7343
AdaBoostClassifier: micro=0.5804, macro=0.5880, weighted=0.5879

## 5. Таблица результатов

In [46]:
from IPython.display import display

In [47]:
df_results = pd.DataFrame(results)
df_results = df_results.sort_values(by='F1_micro', ascending=False)

In [48]:
for dataset_name in dataset_names:
    for clf_name, _ in classifiers.items():
        display(df_results[(df_results['Dataset'] == dataset_name) & (df_results['Classifier'] == clf_name)].head(3))

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
0,emotion,tokenization,binary,DecisionTreeClassifier,0.8680,0.807011,0.868746
4,emotion,tokenization,count,DecisionTreeClassifier,0.8675,0.803927,0.868418
8,emotion,tokenization,tfidf,DecisionTreeClassifier,0.8630,0.806199,0.863499

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
5,emotion,tokenization,count,RandomForestClassifier,0.8870,0.826223,0.886735
9,emotion,tokenization,tfidf,RandomForestClassifier,0.8855,0.821095,0.883758
1,emotion,tokenization,binary,RandomForestClassifier,0.8835,0.825056,0.883021

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
2,emotion,tokenization,binary,GradientBoostingClassifier,0.8445,0.800090,0.845171
6,emotion,tokenization,count,GradientBoostingClassifier,0.8440,0.800222,0.844545
10,emotion,tokenization,tfidf,GradientBoostingClassifier,0.8440,0.800254,0.844057

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
23,emotion,stemming,tfidf,AdaBoostClassifier,0.3545,0.104117,0.195434
19,emotion,stemming,count,AdaBoostClassifier,0.3540,0.104155,0.195514
15,emotion,stemming,binary,AdaBoostClassifier,0.3540,0.104155,0.195514

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
84,news,lemmatization_noun_adj,binary,DecisionTreeClassifier,0.625881,0.626835,0.626725
92,news,lemmatization_noun_adj,tfidf,DecisionTreeClassifier,0.616272,0.617648,0.617476
56,news,tokenization,tfidf,DecisionTreeClassifier,0.616272,0.616957,0.616692

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
77,news,lemmatization,count,RandomForestClassifier,0.772582,0.772862,0.772803
61,news,stemming,binary,RandomForestClassifier,0.768097,0.768236,0.768245
65,news,stemming,count,RandomForestClassifier,0.768097,0.768134,0.768109

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
62,news,stemming,binary,GradientBoostingClassifier,0.763613,0.766636,0.766565
66,news,stemming,count,GradientBoostingClassifier,0.760410,0.763811,0.763689
74,news,lemmatization,binary,GradientBoostingClassifier,0.755285,0.758912,0.758826

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted
75,news,lemmatization,binary,AdaBoostClassifier,0.598334,0.604689,0.604570
83,news,lemmatization,tfidf,AdaBoostClassifier,0.592569,0.599234,0.599410
71,news,stemming,tfidf,AdaBoostClassifier,0.591928,0.598137,0.597961

### Лучшие комбинации

In [87]:
best_for_emotion = {
    'DecisionTreeClassifier': {
        'preprocessing': 'tokenization',
        'vectorizer': 'binary'
    },
    'RandomForestClassifier': {
        'preprocessing': 'tokenization',
        'vectorizer': 'count'
    },
    'GradientBoostingClassifier': {
        'preprocessing': 'tokenization',
        'vectorizer': 'binary'
    },
    'AdaBoostClassifier': {
        'preprocessing': 'stemming',
        'vectorizer': 'tfidf'
    }
}

In [79]:
best_for_news = {
    'DecisionTreeClassifier': {
        'preprocessing': 'lemmatization_noun_adj',
        'vectorizer': 'binary'
    },
    'RandomForestClassifier': {
        'preprocessing': 'lemmatization',
        'vectorizer': 'count'
    },
    'GradientBoostingClassifier': {
        'preprocessing': 'stemming',
        'vectorizer': 'binary'
    },
    'AdaBoostClassifier': {
        'preprocessing': 'lemmatization',
        'vectorizer': 'binary'
    }
}

## 6. Подбор гиперпараметров

### 6.1 Сетки параметров

In [109]:
param_grid_dt = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', None],
    'min_impurity_decrease': [0.0, 0.01]
}

In [131]:
param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

In [107]:
param_grid_gb = {
    'n_estimators': [50, 100],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5],
    'min_samples_split': [5, 10],
    'min_samples_leaf': [2, 4],
    'subsample': [0.8, 1.0]
}

In [110]:
param_grid_ada = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.5, 1.0, 1.5],
    'estimator__max_depth': [1, 2, 3],
    'estimator__min_samples_split': [2, 5],
    'estimator__min_samples_leaf': [1, 2]
}

In [132]:
param_grid = {
    'DecisionTreeClassifier': param_grid_dt,
    'RandomForestClassifier': param_grid_rf,
    'GradientBoostingClassifier': param_grid_gb,
    'AdaBoostClassifier': param_grid_ada
}

In [56]:
result_optimized_hyper = []

### 6.2 Функция подбора параметров

In [113]:
from sklearn.model_selection import RandomizedSearchCV

In [129]:
def tune_classifier(dataset_name, clf_name, prep_name,vec_name, param_grid):
    X_train = processed_train[dataset_name][prep_name]
    X_test = processed_test[dataset_name][prep_name]
    y_train = emotion_train_labels if dataset_name == 'emotion' else news_train_labels
    y_test = emotion_test_labels if dataset_name == 'emotion' else news_test_labels

    if vec_name == 'binary':
        vec = CountVectorizer(binary=True)
    elif vec_name == 'count':
        vec = CountVectorizer(binary=False)
    else:
        vec = TfidfVectorizer()

    X_train_vec = vec.fit_transform(X_train)
    X_test_vec = vec.transform(X_test)

    # Поиск гиперпараметров
    search = RandomizedSearchCV(
        classifiers[clf_name], param_distributions=param_grid, n_iter=20, scoring = 'f1_micro', random_state=42, cv=3, n_jobs=-1
    )
    search.fit(X_train_vec,y_train)
    best_clf = search.best_estimator_
    y_pred = best_clf.predict(X_test_vec)
    f1_micro = f1_score(y_test, y_pred, average='micro')
    f1_macro = f1_score(y_test, y_pred, average='macro')
    f1_weighted = f1_score(y_test, y_pred, average='weighted')

    result_optimized_hyper.append({
        'Dataset': dataset_name,
        'Preprocessing': prep_name,
        'Vectorizer': vec_name,
        'Classifier': clf_name,
        'F1_micro': f1_micro,
        'F1_macro': f1_macro,
        'F1_weighted': f1_weighted,
        'Best_params': str(search.best_params_)
    })

    print(f"{dataset_name} | {prep_name} | {vec_name} | {clf_name} tuned: micro={f1_micro:.4f}")

In [133]:
for clf_name, pipe in best_for_emotion.items():
    tune_classifier('emotion',clf_name, pipe['preprocessing'], pipe['vectorizer'], param_grid[clf_name])

emotion | tokenization | binary | DecisionTreeClassifier tuned: micro=0.7730
emotion | tokenization | count | RandomForestClassifier tuned: micro=0.8940
emotion | tokenization | binary | GradientBoostingClassifier tuned: micro=0.8775
emotion | stemming | tfidf | AdaBoostClassifier tuned: micro=0.3810

In [134]:
for clf_name, pipe in best_for_news.items():
    tune_classifier('news',clf_name, pipe['preprocessing'], pipe['vectorizer'], param_grid[clf_name])

news | lemmatization_noun_adj | binary | DecisionTreeClassifier tuned: micro=0.5490
news | lemmatization | count | RandomForestClassifier tuned: micro=0.7623
news | stemming | binary | GradientBoostingClassifier tuned: micro=0.7771
news | lemmatization | binary | AdaBoostClassifier tuned: micro=0.7329

In [135]:
df_result_optimized_hyper = pd.DataFrame(result_optimized_hyper)
df_result_optimized_hyper = df_result_optimized_hyper.sort_values(by='F1_micro', ascending=False)
display(df_result_optimized_hyper)

,Dataset,Preprocessing,Vectorizer,Classifier,F1_micro,F1_macro,F1_weighted,Best_params
31,emotion,tokenization,count,RandomForestClassifier,0.894000,0.836105,0.891889,"{'n_estimators': 100, 'min_samples_split': 10,..."
5,emotion,tokenization,binary,GradientBoostingClassifier,0.883500,0.836455,0.885052,"{'n_estimators': 100, 'min_samples_split': 5, ..."
10,emotion,tokenization,binary,GradientBoostingClassifier,0.883500,0.836455,0.885052,"{'n_estimators': 100, 'min_samples_split': 5, ..."
14,emotion,tokenization,binary,GradientBoostingClassifier,0.883500,0.836455,0.885052,"{'n_estimators': 100, 'min_samples_split': 5, ..."
2,emotion,tokenization,binary,GradientBoostingClassifier,0.883500,0.836455,0.885052,"{'n_estimators': 100, 'min_samples_split': 5, ..."
32,emotion,tokenization,binary,GradientBoostingClassifier,0.877500,0.832051,0.878433,"{'subsample': 0.8, 'n_estimators': 100, 'min_s..."
18,emotion,stemming,binary,GradientBoostingClassifier,0.854500,0.803753,0.855635,"{'n_estimators': 100, 'min_samples_split': 5, ..."
36,news,stemming,binary,GradientBoostingClassifier,0.777066,0.778927,0.778752,"{'subsample': 0.8, 'n_estimators': 100, 'min_s..."
24,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
29,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
26,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
27,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
25,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
28,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
30,emotion,tokenization,binary,DecisionTreeClassifier,0.773000,0.735353,0.771289,"{'min_samples_split': 10, 'min_samples_leaf': ..."
35,news,lemmatization,count,RandomForestClassifier,0.762332,0.762632,0.762639,"{'n_estimators': 200, 'min_samples_split': 2, ..."
37,news,lemmatization,binary,AdaBoostClassifier,0.732864,0.735361,0.735221,"{'n_estimators': 300, 'learning_rate': 1.0, 'e..."
3,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
22,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
8,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
0,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
6,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
20,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
12,emotion,tokenization,binary,DecisionTreeClassifier,0.712500,0.682717,0.708600,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
16,emotion,lemmatization_noun_adj,binary,DecisionTreeClassifier,0.658500,0.607588,0.658164,"{'min_samples_split': 2, 'min_samples_leaf': 4..."
34,news,lemmatization_noun_adj,binary,DecisionTreeClassifier,0.549007,0.551652,0.551651,"{'min_samples_split': 10, 'min_samples_leaf': ..."
17,emotion,lemmatization,count,RandomForestClassifier,0.479000,0.215088,0.385410,"{'n_estimators': 100, 'min_samples_split': 2, ..."
1,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
4,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
13,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
9,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
7,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
23,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
21,emotion,tokenization,count,RandomForestClassifier,0.462000,0.208478,0.368529,"{'n_estimators': 100, 'min_samples_split': 2, ..."
33,emotion,stemming,tfidf,AdaBoostClassifier,0.381000,0.356057,0.338671,"{'n_estimators': 300, 'learning_rate': 1.5, 'e..."
11,emotion,stemming,tfidf,AdaBoostClassifier,0.358000,0.136147,0.208932,"{'n_estimators': 100, 'learning_rate': 1.0, 'e..."
15,emotion,stemming,tfidf,AdaBoostClassifier,0.358000,0.136147,0.208932,"{'n_estimators': 100, 'learning_rate': 1.0, 'e..."
19,emotion,lemmatization,binary,AdaBoostClassifier,0.353500,0.120417,0.205986,"{'n_estimators': 50, 'learning_rate': 1.0, 'es..."

### 6.3 Выводы

1) Для датасета emotion

- RandomForestClassifier: после подбора микро‑F1 вырос с 0,887 до 0,894

- GradientBoostingClassifier: значительный рост с 0,8445 до 0,8835

- DecisionTreeClassifier: ухудшение с 0,868 до 0,773 – возможно, сетка параметров была недостаточно проработана

- AdaBoostClassifier: микро‑F1 вырос с 0,3545 до 0,381, но всё ещё остаётся крайне низким - эта модель плохо справляется с задачей классификации эмоций

2) Для датасета news

- RandomForestClassifier: результат практически не изменился: с 0,7726 до 0,7623)

- GradientBoostingClassifier: улучшение с 0,7636 до 0,7771 - подтверждает, что бустинговые модели выигрывают от тонкой настройки

- DecisionTreeClassifier: сильное падение с 0,6259 до 0,5490

- AdaBoostClassifier: заметный рост с 0,5983 до 0,7329 - подбор существенно повысил

3) Общие мысли:
Причинами ухудшения могут быть:

 - ограниченное число итераций случайного поиска (n_iter=20),

 - использование 3‑кратной кросс‑валидации

- неполное покрытие пространства гиперпараметров

### 7. LSA

In [136]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import TruncatedSVD

In [137]:
components = [50,100,200,300,500]

In [138]:
results_LSA = []

In [139]:
def run_lsa(dataset_name,prep_name,clf_name,components_list):
    X_train = processed_train[dataset_name][prep_name]
    X_test = processed_test[dataset_name][prep_name]
    y_train = emotion_train_labels if dataset_name == 'emotion' else news_train_labels
    y_test = emotion_test_labels if dataset_name == 'emotion' else news_test_labels

    # Без LSA
    pipe_base = Pipeline([
        ('tfidf', TfidfVectorizer()),
        ('clf', classifiers[clf_name])
    ])

    pipe_base.fit(X_train,y_train)
    y_pred_base = pipe_base.predict(X_test)
    f1_micro_base = f1_score(y_test, y_pred_base, average='micro')
    f1_macro_base = f1_score(y_test, y_pred_base, average='macro')
    f1_weighted_base = f1_score(y_test, y_pred_base, average='weighted')

    results_LSA.append({
        'Dataset': dataset_name,
        'Preprocessing': prep_name,
        'Vectorizer': 'tf-idf',
        'Classifier': clf_name,
        'F1_micro': f1_micro_base,
        'F1_macro': f1_macro_base,
        'F1_weighted': f1_weighted_base,
    })

    print(f"{dataset_name} | {prep_name} | {clf_name} |micro={f1_micro_base:.4f}")

    for n in components_list:
        pipe_lsa = Pipeline([
            ('tfidf', TfidfVectorizer()),
            ('lsa', TruncatedSVD(n_components=n, random_state=42)),
            ('clf', classifiers[clf_name])
        ])

        pipe_lsa.fit(X_train,y_train)
        y_pred_lsa = pipe_lsa.predict(X_test)
        f1_micro_lsa = f1_score(y_test, y_pred_lsa, average='micro')
        f1_macro_lsa = f1_score(y_test, y_pred_lsa, average='macro')
        f1_weighted_lsa = f1_score(y_test, y_pred_lsa, average='weighted')

        results_LSA.append({
            'Dataset': dataset_name,
            'Preprocessing': prep_name,
            'Vectorizer': f"LSA_{n}",
            'Classifier': clf_name,
            'F1_micro': f1_micro_lsa,
            'F1_macro': f1_macro_lsa,
            'F1_weighted': f1_weighted_lsa,
        })

        print(f"  n={n}: micro={f1_micro_lsa:.4f}")

In [140]:
best_for_emotion_without_GBM = {
     'DecisionTreeClassifier': {
        'preprocessing': 'tokenization',
        'vectorizer': 'binary'
    },
    'RandomForestClassifier': {
        'preprocessing': 'tokenization',
        'vectorizer': 'count'
    },
    'AdaBoostClassifier': {
        'preprocessing': 'stemming',
        'vectorizer': 'tfidf'
    }
}

In [141]:
best_for_news_without_GBM = {
    'DecisionTreeClassifier': {
        'preprocessing': 'lemmatization_noun_adj',
        'vectorizer': 'binary'
    },
    'RandomForestClassifier': {
        'preprocessing': 'lemmatization',
        'vectorizer': 'count'
    },
    'AdaBoostClassifier': {
        'preprocessing': 'lemmatization',
        'vectorizer': 'binary'
    }
}

In [142]:
for clf_name, pipe in best_for_emotion_without_GBM.items():
    run_lsa('emotion', pipe['preprocessing'], clf_name, components)

emotion | tokenization | DecisionTreeClassifier |micro=0.8630
  n=50: micro=0.3060
  n=100: micro=0.3520
  n=200: micro=0.3955
  n=300: micro=0.3880
  n=500: micro=0.4315
emotion | tokenization | RandomForestClassifier |micro=0.8855
  n=50: micro=0.4690
  n=100: micro=0.5335
  n=200: micro=0.5900
  n=300: micro=0.6340
  n=500: micro=0.6560
emotion | stemming | AdaBoostClassifier |micro=0.7340
  n=50: micro=0.3500
  n=100: micro=0.4075
  n=200: micro=0.4865
  n=300: micro=0.4940
  n=500: micro=0.5065

In [143]:
for clf_name, pipe in best_for_news_without_GBM.items():
    run_lsa('news', pipe['preprocessing'], clf_name, components)

news | lemmatization_noun_adj | DecisionTreeClassifier |micro=0.6163
  n=50: micro=0.5990
  n=100: micro=0.6092
  n=200: micro=0.6163
  n=300: micro=0.6137
  n=500: micro=0.6182
news | lemmatization | RandomForestClassifier |micro=0.7675
  n=50: micro=0.7290
  n=100: micro=0.7316
  n=200: micro=0.7348
  n=300: micro=0.7380
  n=500: micro=0.7309
news | lemmatization | AdaBoostClassifier |micro=0.6534
  n=50: micro=0.6400
  n=100: micro=0.6586
  n=200: micro=0.6618
  n=300: micro=0.6528
  n=500: micro=0.6534

In [144]:
df_results_LSA = pd.DataFrame(results_LSA)
df_results_LSA.sort_values(by='F1_micro', ascending=False)
display(results_LSA)

[{'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.863,
  'F1_macro': 0.8061988502341788,
  'F1_weighted': 0.863498855490817},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.306,
  'F1_macro': 0.2221763453272557,
  'F1_weighted': 0.307422497618017},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.352,
  'F1_macro': 0.2641248112985211,
  'F1_weighted': 0.3556936975581032},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.3955,
  'F1_macro': 0.3048929316628195,
  'F1_weighted': 0.39832857921695636},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.388,
  'F1_macro': 0.2976309887864418,
  'F1_weighted': 0.39196800820252337},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.4315,
  'F1_macro': 0.35746819695770204,
  'F1_weighted': 0.4344675297874282},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.8855,
  'F1_macro': 0.8210949871279304,
  'F1_weighted': 0.8837578292139495},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.469,
  'F1_macro': 0.2731034879270282,
  'F1_weighted': 0.4058069981419513},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.5335,
  'F1_macro': 0.34184156183097864,
  'F1_weighted': 0.48030838751681615},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.59,
  'F1_macro': 0.4103110089688236,
  'F1_weighted': 0.5470543300373057},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.634,
  'F1_macro': 0.47015417772709883,
  'F1_weighted': 0.5969456465916732},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.656,
  'F1_macro': 0.519608502632795,
  'F1_weighted': 0.6247634086067096},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'tf-idf',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.734,
  'F1_macro': 0.6780390895752332,
  'F1_weighted': 0.7336707614518801},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_50',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.35,
  'F1_macro': 0.2643042256012374,
  'F1_weighted': 0.34116846545179746},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_100',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.4075,
  'F1_macro': 0.3112632991427051,
  'F1_weighted': 0.3959465643863391},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_200',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.4865,
  'F1_macro': 0.3658035874398941,
  'F1_weighted': 0.47301267022416116},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_300',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.494,
  'F1_macro': 0.3957613751696811,
  'F1_weighted': 0.4846535056246292},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_500',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.5065,
  'F1_macro': 0.4062122064408678,
  'F1_weighted': 0.4954249744998387},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6162716207559257,
  'F1_macro': 0.6176480184160199,
  'F1_weighted': 0.6174759042287555},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.5989750160153747,
  'F1_macro': 0.5997082470423005,
  'F1_weighted': 0.5997227802638735},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6092248558616271,
  'F1_macro': 0.6088817030908295,
  'F1_weighted': 0.6090393960230767},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6162716207559257,
  'F1_macro': 0.6151172377461516,
  'F1_weighted': 0.6152639779279986},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6137091607943626,
  'F1_macro': 0.6134022791021144,
  'F1_weighted': 0.613563206633342},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.618193465727098,
  'F1_macro': 0.6185324388018816,
  'F1_weighted': 0.6187763850966699},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7674567584881486,
  'F1_macro': 0.7677392811743747,
  'F1_weighted': 0.7676967968047254},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7290198590647021,
  'F1_macro': 0.7293325643850078,
  'F1_weighted': 0.7294063769080689},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7315823190262652,
  'F1_macro': 0.7319199638424069,
  'F1_weighted': 0.7320175445574947},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7347853939782191,
  'F1_macro': 0.735071602910282,
  'F1_weighted': 0.7351774199915786},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.737988468930173,
  'F1_macro': 0.7385069019732453,
  'F1_weighted': 0.7385532386508761},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7309417040358744,
  'F1_macro': 0.7316528747363227,
  'F1_weighted': 0.7317826532854181},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6534272901985907,
  'F1_macro': 0.6535507207558846,
  'F1_weighted': 0.653409640841556},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6399743754003844,
  'F1_macro': 0.6400957991736774,
  'F1_weighted': 0.6402065182410793},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6585522101217168,
  'F1_macro': 0.658693911178001,
  'F1_weighted': 0.6588280782030724},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6617552850736708,
  'F1_macro': 0.6620120825669167,
  'F1_weighted': 0.6620703292262115},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6527866752081999,
  'F1_macro': 0.6531973846739516,
  'F1_weighted': 0.6532531681753317},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6534272901985907,
  'F1_macro': 0.6540294327041843,
  'F1_weighted': 0.6541845486520276}]

## 8. LSA + только сущ и прил

In [145]:
prep_noun_adj = 'lemmatization_noun_adj'

In [146]:
for clf_name, pipe in best_for_emotion_without_GBM.items():
    run_lsa('emotion', prep_noun_adj, clf_name, components)

emotion | lemmatization_noun_adj | DecisionTreeClassifier |micro=0.6780
  n=50: micro=0.3805
  n=100: micro=0.4070
  n=200: micro=0.4395
  n=300: micro=0.4670
  n=500: micro=0.4705
emotion | lemmatization_noun_adj | RandomForestClassifier |micro=0.7120
  n=50: micro=0.5120
  n=100: micro=0.5480
  n=200: micro=0.6050
  n=300: micro=0.6155
  n=500: micro=0.6205
emotion | lemmatization_noun_adj | AdaBoostClassifier |micro=0.6195
  n=50: micro=0.4785
  n=100: micro=0.5060
  n=200: micro=0.5420
  n=300: micro=0.5560
  n=500: micro=0.5565

In [147]:
for clf_name, pipe in best_for_news_without_GBM.items():
    run_lsa('news', prep_noun_adj, clf_name, components)

news | lemmatization_noun_adj | DecisionTreeClassifier |micro=0.6163
  n=50: micro=0.5990
  n=100: micro=0.6092
  n=200: micro=0.6163
  n=300: micro=0.6137
  n=500: micro=0.6182
news | lemmatization_noun_adj | RandomForestClassifier |micro=0.7438
  n=50: micro=0.7156
  n=100: micro=0.7175
  n=200: micro=0.7098
  n=300: micro=0.7149
  n=500: micro=0.7021
news | lemmatization_noun_adj | AdaBoostClassifier |micro=0.6413
  n=50: micro=0.6534
  n=100: micro=0.6233
  n=200: micro=0.6323
  n=300: micro=0.6374
  n=500: micro=0.6451

In [148]:
df_results_LSA.sort_values(by='F1_micro', ascending=False)
display(results_LSA)

[{'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.863,
  'F1_macro': 0.8061988502341788,
  'F1_weighted': 0.863498855490817},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.306,
  'F1_macro': 0.2221763453272557,
  'F1_weighted': 0.307422497618017},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.352,
  'F1_macro': 0.2641248112985211,
  'F1_weighted': 0.3556936975581032},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.3955,
  'F1_macro': 0.3048929316628195,
  'F1_weighted': 0.39832857921695636},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.388,
  'F1_macro': 0.2976309887864418,
  'F1_weighted': 0.39196800820252337},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.4315,
  'F1_macro': 0.35746819695770204,
  'F1_weighted': 0.4344675297874282},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.8855,
  'F1_macro': 0.8210949871279304,
  'F1_weighted': 0.8837578292139495},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.469,
  'F1_macro': 0.2731034879270282,
  'F1_weighted': 0.4058069981419513},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.5335,
  'F1_macro': 0.34184156183097864,
  'F1_weighted': 0.48030838751681615},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.59,
  'F1_macro': 0.4103110089688236,
  'F1_weighted': 0.5470543300373057},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.634,
  'F1_macro': 0.47015417772709883,
  'F1_weighted': 0.5969456465916732},
 {'Dataset': 'emotion',
  'Preprocessing': 'tokenization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.656,
  'F1_macro': 0.519608502632795,
  'F1_weighted': 0.6247634086067096},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'tf-idf',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.734,
  'F1_macro': 0.6780390895752332,
  'F1_weighted': 0.7336707614518801},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_50',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.35,
  'F1_macro': 0.2643042256012374,
  'F1_weighted': 0.34116846545179746},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_100',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.4075,
  'F1_macro': 0.3112632991427051,
  'F1_weighted': 0.3959465643863391},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_200',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.4865,
  'F1_macro': 0.3658035874398941,
  'F1_weighted': 0.47301267022416116},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_300',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.494,
  'F1_macro': 0.3957613751696811,
  'F1_weighted': 0.4846535056246292},
 {'Dataset': 'emotion',
  'Preprocessing': 'stemming',
  'Vectorizer': 'LSA_500',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.5065,
  'F1_macro': 0.4062122064408678,
  'F1_weighted': 0.4954249744998387},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6162716207559257,
  'F1_macro': 0.6176480184160199,
  'F1_weighted': 0.6174759042287555},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.5989750160153747,
  'F1_macro': 0.5997082470423005,
  'F1_weighted': 0.5997227802638735},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6092248558616271,
  'F1_macro': 0.6088817030908295,
  'F1_weighted': 0.6090393960230767},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6162716207559257,
  'F1_macro': 0.6151172377461516,
  'F1_weighted': 0.6152639779279986},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6137091607943626,
  'F1_macro': 0.6134022791021144,
  'F1_weighted': 0.613563206633342},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.618193465727098,
  'F1_macro': 0.6185324388018816,
  'F1_weighted': 0.6187763850966699},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7674567584881486,
  'F1_macro': 0.7677392811743747,
  'F1_weighted': 0.7676967968047254},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7290198590647021,
  'F1_macro': 0.7293325643850078,
  'F1_weighted': 0.7294063769080689},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7315823190262652,
  'F1_macro': 0.7319199638424069,
  'F1_weighted': 0.7320175445574947},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7347853939782191,
  'F1_macro': 0.735071602910282,
  'F1_weighted': 0.7351774199915786},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.737988468930173,
  'F1_macro': 0.7385069019732453,
  'F1_weighted': 0.7385532386508761},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7309417040358744,
  'F1_macro': 0.7316528747363227,
  'F1_weighted': 0.7317826532854181},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'tf-idf',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6534272901985907,
  'F1_macro': 0.6535507207558846,
  'F1_weighted': 0.653409640841556},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_50',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6399743754003844,
  'F1_macro': 0.6400957991736774,
  'F1_weighted': 0.6402065182410793},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_100',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6585522101217168,
  'F1_macro': 0.658693911178001,
  'F1_weighted': 0.6588280782030724},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_200',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6617552850736708,
  'F1_macro': 0.6620120825669167,
  'F1_weighted': 0.6620703292262115},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_300',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6527866752081999,
  'F1_macro': 0.6531973846739516,
  'F1_weighted': 0.6532531681753317},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization',
  'Vectorizer': 'LSA_500',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6534272901985907,
  'F1_macro': 0.6540294327041843,
  'F1_weighted': 0.6541845486520276},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.678,
  'F1_macro': 0.6037799215708647,
  'F1_weighted': 0.6758860798938063},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.3805,
  'F1_macro': 0.28164155591798157,
  'F1_weighted': 0.3817121484365937},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.407,
  'F1_macro': 0.3068787827865765,
  'F1_weighted': 0.4079657200272434},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.4395,
  'F1_macro': 0.34879261042856863,
  'F1_weighted': 0.43709561590450635},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.467,
  'F1_macro': 0.38276159147013383,
  'F1_weighted': 0.4689311141841405},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.4705,
  'F1_macro': 0.3793321773117153,
  'F1_weighted': 0.4707166366976464},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.712,
  'F1_macro': 0.6397749752418465,
  'F1_weighted': 0.7077125066787943},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.512,
  'F1_macro': 0.3546271595742804,
  'F1_weighted': 0.47528060284961193},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.548,
  'F1_macro': 0.40017056688114744,
  'F1_weighted': 0.5170656227765433},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.605,
  'F1_macro': 0.4721838036967265,
  'F1_weighted': 0.5805191699046683},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.6155,
  'F1_macro': 0.49433947371569564,
  'F1_weighted': 0.5934606916123967},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.6205,
  'F1_macro': 0.5002402260954699,
  'F1_weighted': 0.5983743022265253},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6195,
  'F1_macro': 0.533347120170499,
  'F1_weighted': 0.6106404686095281},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.4785,
  'F1_macro': 0.3434693878130899,
  'F1_weighted': 0.4591699652047741},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.506,
  'F1_macro': 0.38358488544339037,
  'F1_weighted': 0.48955551269812886},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.542,
  'F1_macro': 0.4324826360784266,
  'F1_weighted': 0.5287131332615005},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.556,
  'F1_macro': 0.45572283606187863,
  'F1_weighted': 0.5448630063880346},
 {'Dataset': 'emotion',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.5565,
  'F1_macro': 0.4394278706713132,
  'F1_weighted': 0.5418170368881804},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6162716207559257,
  'F1_macro': 0.6176480184160199,
  'F1_weighted': 0.6174759042287555},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.5989750160153747,
  'F1_macro': 0.5997082470423005,
  'F1_weighted': 0.5997227802638735},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6092248558616271,
  'F1_macro': 0.6088817030908295,
  'F1_weighted': 0.6090393960230767},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6162716207559257,
  'F1_macro': 0.6151172377461516,
  'F1_weighted': 0.6152639779279986},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.6137091607943626,
  'F1_macro': 0.6134022791021144,
  'F1_weighted': 0.613563206633342},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'DecisionTreeClassifier',
  'F1_micro': 0.618193465727098,
  'F1_macro': 0.6185324388018816,
  'F1_weighted': 0.6187763850966699},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.74375400384369,
  'F1_macro': 0.7451587072009256,
  'F1_weighted': 0.7449981518465448},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7155669442664958,
  'F1_macro': 0.7162131369776095,
  'F1_weighted': 0.7162350153130602},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7174887892376681,
  'F1_macro': 0.7185291938614669,
  'F1_weighted': 0.7185974568388758},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7098014093529789,
  'F1_macro': 0.7106385145492182,
  'F1_weighted': 0.7106731296851926},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7149263292761051,
  'F1_macro': 0.7155244203418645,
  'F1_weighted': 0.7155841080339069},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'RandomForestClassifier',
  'F1_micro': 0.7021140294682896,
  'F1_macro': 0.7030985165831432,
  'F1_weighted': 0.7031752779815902},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'tf-idf',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6412556053811659,
  'F1_macro': 0.6418476780273116,
  'F1_weighted': 0.6416907018834925},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_50',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6534272901985907,
  'F1_macro': 0.6542364760121623,
  'F1_weighted': 0.6544230859345284},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_100',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6233183856502242,
  'F1_macro': 0.6232012458958595,
  'F1_weighted': 0.6233921813924009},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_200',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6322869955156951,
  'F1_macro': 0.6321279297260727,
  'F1_weighted': 0.6323020487227751},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_300',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6374119154388213,
  'F1_macro': 0.6368421951873826,
  'F1_weighted': 0.6370350079532153},
 {'Dataset': 'news',
  'Preprocessing': 'lemmatization_noun_adj',
  'Vectorizer': 'LSA_500',
  'Classifier': 'AdaBoostClassifier',
  'F1_micro': 0.6450992953235106,
  'F1_macro': 0.6458625035656609,
  'F1_weighted': 0.6459983018955072}]

### Выводы

1) На датасете emotion
- LSA во всех экспериментах приводила к резкому падению F1‑меры по сравнению с полной TF‑IDF матрицей. Даже при 500 компонентах качество оставалось на 20–30 процентных пунктов ниже исходного. Это объясняется тем, что в датасете эмоций относительно мало документов и классов, а понижение размерности удаляет важные различительные признаки.

2) На датасете news
Результаты более разнообразны:

- Для RandomForestClassifier LSA ухудшала качество, но падение было не столь катастрофичным (с ~0,767 до ~0,738 при 300 компонентах).

- Для DecisionTreeClassifier при использовании LSA качество оставалось на том же уровне (0,616–0,618), а в одном случае (500 компонент) даже немного превышало tf-idf

- Для AdaBoostClassifier LSA улучшала результаты: на lemmatization + TF‑IDF базовая микро‑F1 = 0,6534, а после LSA с 200 компонентами – 0,6618; на lemmatization_noun_adj с 50 компонентами – 0,6534 против исходных 0,6413.

3) Общие мысли
- LSA может быть полезным инструментом для ускорения обучения и уменьшения памяти, особенно когда задача допускает некоторое снижение точности или когда исходная размерность чрезмерно велика.

- На небольших наборах данных или в задачах с малым числом классов (как emotion) применение LSA нецелесообразно, так как потеря информации перевешивает выгоду от уменьшения размерности.

- В более сложных задачах с большим объёмом текста (как 20 newsgroups) LSA может сохранить качество или даже улучшить его для некоторых классификаторов, особенно для ансамблевых методов (AdaBoost).